//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRTR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRTR.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File info file is corrupted..
        /// </summary>
        internal static string CorruptedFileInfo {
            get {
                return ResourceManager.GetString("CorruptedFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration datafile is corrupted.
        /// </summary>
        internal static string CorruptedRestoration {
            get {
                return ResourceManager.GetString("CorruptedRestoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation datafile is corrupted.
        /// </summary>
        internal static string CorruptedTranslation {
            get {
                return ResourceManager.GetString("CorruptedTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen game&apos;s install directory isn&apos;t contain data file.
        /// </summary>
        internal static string DataFilesNotFound {
            get {
                return ResourceManager.GetString("DataFilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFile error: Wrong FAT entry number: {0:d}.
        /// </summary>
        internal static string FATEntryCountError {
            get {
                return ResourceManager.GetString("FATEntryCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game isn&apos;t selected.
        /// </summary>
        internal static string GameIsNotSelected {
            get {
                return ResourceManager.GetString("GameIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen game&apos;s install directory does not exist.
        /// </summary>
        internal static string InstallDirectoryNotExist {
            get {
                return ResourceManager.GetString("InstallDirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid language code.
        /// </summary>
        internal static string InvalidLanguageCode {
            get {
                return ResourceManager.GetString("InvalidLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter, expected {0}.
        /// </summary>
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sort mode.
        /// </summary>
        internal static string InvalidSortMode {
            get {
                return ResourceManager.GetString("InvalidSortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid stored file info.
        /// </summary>
        internal static string InvalidStoredFileInfo {
            get {
                return ResourceManager.GetString("InvalidStoredFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid text replace settings.
        /// </summary>
        internal static string InvalidTextReplaceSettings {
            get {
                return ResourceManager.GetString("InvalidTextReplaceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string LangCzech {
            get {
                return ResourceManager.GetString("LangCzech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanol.
        /// </summary>
        internal static string LangEspanol {
            get {
                return ResourceManager.GetString("LangEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string LangFrench {
            get {
                return ResourceManager.GetString("LangFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string LangGerman {
            get {
                return ResourceManager.GetString("LangGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string LangItalian {
            get {
                return ResourceManager.GetString("LangItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language.
        /// </summary>
        internal static string LangNoLang {
            get {
                return ResourceManager.GetString("LangNoLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string LangPolish {
            get {
                return ResourceManager.GetString("LangPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LangRussian {
            get {
                return ResourceManager.GetString("LangRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file is too big.
        /// </summary>
        internal static string NewFileIsTooBig {
            get {
                return ResourceManager.GetString("NewFileIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotAvailableShort {
            get {
                return ResourceManager.GetString("NotAvailableShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown cinematics block type.
        /// </summary>
        internal static string ParseErrorBlockTypeError {
            get {
                return ResourceManager.GetString("ParseErrorBlockTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size mismatch.
        /// </summary>
        internal static string ParseErrorSizeMismatch {
            get {
                return ResourceManager.GetString("ParseErrorSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too big.
        /// </summary>
        internal static string ParseErrorTooBig {
            get {
                return ResourceManager.GetString("ParseErrorTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block must be initialized before translate.
        /// </summary>
        internal static string TranslatingUninitializedBlock {
            get {
                return ResourceManager.GetString("TranslatingUninitializedBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation data file isn&apos;t found for chosen game.
        /// </summary>
        internal static string TranslationDataFileNotFound {
            get {
                return ResourceManager.GetString("TranslationDataFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation informations isn&apos;t initialized.
        /// </summary>
        internal static string TranslationInformationsNotInitialized {
            get {
                return ResourceManager.GetString("TranslationInformationsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program version: {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
